name: Build and Release
on:
  # # Indicates I want to run this workflow on all branches, PR, and tags
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: [ "master" ]
jobs:
  release:
    name: Release
    needs: [build]
    # Can't use non-semvar for the testing tag
    # https://github.com/orgs/goreleaser/discussions/3708
    if: ( startsWith( github.ref, 'refs/tags/v' ) ||
            startsWith(github.ref, 'refs/tags/v0.0.0-rc') )
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v3

      # Download all artifacts
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      # Goreleaser
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          # Run goreleaser and ignore non-committed files (downloaded artifacts)
          args: release --clean --skip=validate --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  terraform-provider-release:
    name: 'Terraform Provider Release'
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v5
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
    with:
      setup-go-version-file: 'go.mod'
