name: Github Release and Terraform Release
on:
  # # Indicates I want to run this workflow on all branches, PR, and tags
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: [ "master" ]
jobs:
  release:
    name: Release
    needs: [tests]
    # Can't use non-semvar for the testing tag
    # https://github.com/orgs/goreleaser/discussions/3708
    if: ( startsWith( github.ref, 'refs/tags/v' ) ||
            startsWith(github.ref, 'refs/tags/v0.0.0-rc') )
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4

      # Goreleaser
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          # Run goreleaser and ignore non-committed files (downloaded artifacts)
          args: release --clean --skip=validate --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  terraform-provider-release:
    needs: [release]
    name: 'Terraform Provider Release'
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v5
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
    with:
      setup-go-version-file: 'go.mod'
